HourClass/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import routers
# from rest_framework.authtoken import views
from account.views import SignUpAPI, PasswordResetTokenAPI, PasswordResetAuthAPI
from consumer.views import ClientMemberViewSet
from service.views import ServicesViewSet, GetEventApi
from staffer.views import StaffMemberViewSet
from event.views import (
    ClientEventViewSet,
    GetDateForEventApiList,
    GetAvailForAppointmentList,
    EventCreateAPI,
    EventUpdateAPI,
    EventCancelAPI
    )
from consortium.views import CompanyDetailsViewSet
from source_utils.views import HomeDetail
from source_utils.permission_mixins import CustomAuthToken, ChangePasswordView
# from rest_framework.authtoken.views import ChangePasswordView

from django.contrib import admin

router = routers.DefaultRouter()
router.register(r'services', ServicesViewSet)
router.register(r'recent_appointments', ClientEventViewSet)
router.register(r'active_staff', StaffMemberViewSet)
router.register(r'company_details', CompanyDetailsViewSet)
# router.register(r'server_time', GetDateForEventApiList, base_name='server_time')


from rest_auth.views import LoginView


urlpatterns = [
    path("", HomeDetail.as_view(), name="home"),
    re_path(r'^schedule/(?P<day>-?\d+)/$', HomeDetail.as_view(), name="home_schedule"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', CustomAuthToken.as_view()),
    path('rest-auth/', include('rest_auth.urls')),
    path('sign_up/', SignUpAPI.as_view(), name='sign_up'),
    path('get_reset_pin/', PasswordResetTokenAPI.as_view(), name='get_reset_pin'),
    path('get_reset_auth/', PasswordResetAuthAPI.as_view(), name='get_reset_auth'),
    # url(r'^$',EmployeeTemplateView.as_view(emp='employees')
    path('available_appt_dates/', GetDateForEventApiList.as_view(), name='available_appt_dates'),
    path('available_appt_times/', GetAvailForAppointmentList.as_view(), name='available_appt_times'),
    path('create_event_api/', EventCreateAPI.as_view(), name='create_event_api'),
    path('update_event_api/', EventUpdateAPI.as_view(), name='update_event_api'),
    path('cancel_event_api/', EventCancelAPI.as_view(), name='cancel_event_api'),
    path('get_event_api/', GetEventApi.as_view(), name='get_event_api'),
    path('rest-auth/login/', LoginView.as_view(), name='rest_login'),
    path('reset_password/', ChangePasswordView.as_view(), name='reset_password'),

    path("service/", include("service.urls")),
    path("event/", include("event.urls")),
    path("client/", include("consumer.urls")),
    path("staff_schedule/", include("staff_sced.urls")),
    path("staff/", include("staffer.urls")),
    path("company/", include("consortium.urls")),

    path("client_users/<str:username>/<str:hello>/", ClientMemberViewSet.as_view({'get': 'list'})),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# from rest_framework.authtoken import views
# urlpatterns += [
#     url(r'^api-token-auth/', views.obtain_auth_token)
# ]

event/urls.py
from django.urls import path, re_path

from .views import (
    AllEventList,
    AvailForAppointmentList,
    # AvailabilityList,
    # ClientApptCreate,
    ClientEventCreate,
    ClientEventUpdate,
    GetDateForEvent,
    GetClientForEvent,
    GetTypeOfEvent,
    GetStaffForEvent,
    # MyAvailCreate,
    # MyAvailUpdate,
    MyEventList,    
    StaffEventUpdate
)


app_name = 'event'
urlpatterns = [
    path('my_events/',
        MyEventList.as_view(),
        name="my_event_list"),
    # path('<slug:slug>/avail/',
    #     AvailabilityList.as_view(),
    #     name="staff_avail"),
    path('all_events/',
        AllEventList.as_view(),
        name="all_event_list"),
    path('add/event/',
        GetClientForEvent.as_view(),
        name="start_new_client_appt"),
    path('add/<int:client>/<str:ev_type>/',
        GetTypeOfEvent.as_view(),
        name="add_service_type"),
    path('add/<slug:service>/<int:client>/<str:ev_type>/',
        GetStaffForEvent.as_view(),
        name="add_staff_to_appt"),

    path('add/<str:selected_staff>/<slug:service>/<int:client>/<str:ev_type>/',
        GetDateForEvent.as_view(),
        name="add_date_to_appt"),
    
    path('<int:pk>/update/',
        ClientEventUpdate.as_view(),
        name="event_update"),
    path('staff_event/<int:pk>/update/',
        StaffEventUpdate.as_view(),
        name="staff_event_update"),

    path('find/<str:selected_staff>/<str:date>/<str:staff_name>/<slug:service>/<int:client>/<str:ev_type>/',
        AvailForAppointmentList.as_view(),
        name="avail_appt_list"),

    path('create/<str:start>/<str:staff>/<slug:service>/<int:client>/<str:ev_type>/',
        ClientEventCreate.as_view(),
        name="client_event_create"),
    # path('<int:pk>/avail_update/',
    #     MyAvailUpdate.as_view(),
    #     name="my_avail_update"),
    # path('<int:pk>/avail_create/',
    #     MyAvailCreate.as_view(),
    #     name="avail_create"),



    
    # url(r'^base/(?P<slug>[-\w]+)/update/$', BaseTypeUpdate.as_view(),
    #     name="service_update"),

    # url(r'^service/manage/(?P<slug>[-\w]+)/$', manage_service,
    #     name="service_manage"),
]

staff_sced/urls.py
from django.urls import path, re_path

from staff_sced.views import (
    AvailabilityList,
    MyAvailCreate,
    MyAvailUpdate
)


app_name = 'staff_sced'
urlpatterns = [
    path('<slug:slug>/avail/',
        AvailabilityList.as_view(),
        name="staff_avail"),   
    path('<int:pk>/avail_update/',
        MyAvailUpdate.as_view(),
        name="my_avail_update"),
    path('<int:pk>/avail_create/',
        MyAvailCreate.as_view(),
        name="avail_create")
]

HourClass/templates/staff/signup.html
{% extends "homepage.html" %}

{% load account_tags %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Sign up" %}{% endblock %}

{% block caption %}
    <div class="row">
        <div class="col-md-4">
            <form id="signup_form" method="post" action="{% url "account_signup" %}" autocapitalize="off" {% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
                <legend>{% trans "Sign up" %}</legend>
                {% csrf_token %}
                {{ form|crispy }}
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                <button type="submit" class="btn btn-primary">{% trans "Sign up" %}</button>
            </form>
            <p class="login-signup">
                <small>
                    {% trans "Already have an account?" %}  <strong><a href="{% urlnext 'account_login' %}">{% trans "Log in" %}</a></strong>
                </small>
            </p>
        </div>
    </div>
{% endblock %}
{% block main_theme %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#id_username').focus();
        });
    </script>
{% endblock %}

HourClass/templates/staff/staff_avail_list.html
{% extends "homepage.html" %}

{% load i18n %}

{% block caption %}
  <div class="feature-columns row">
    <div class="col-md text-center">
      <h3>{{ staff.get_friendly_name }}'s Availability {% if user == staff.base_account.user or user.account.is_manager %}{% if avail %}<a class="day_nav" href="{% url 'staff_sced:avail_create' staff.pk %}">Add</a>{% endif %}{% endif %}</h3>
          <ul class="list-unstyled">
          {% for day in staff_avail %}
              <li>{% if user == staff.base_account.user or user.account.is_manager %}<a class="day_nav" href="{{ day.get_absolute_url }}">{% if day.not_avail %}{{ day.day }} - Day Off{% else %}{{ day.display_schedule }}{% endif %}</a>{% else %}{% if day.not_avail %}{{ day.day }} - Day Off{% else %}{{ day.display_schedule }}{% endif %}{% endif %}
              </li>
              {% empty %}
              <li>{% if user == staff.base_account.user or user.account.is_manager %}<a class="day_nav" href="{% url 'staff_sced:avail_create' staff.pk %}">Not Entered Yet</a>{% else %}Not Entered Yet{% endif %}</li>
          {% endfor %}
          </ul>
    </div>
  </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
{% endblock %}

HourClass/templates/staff/staff_list.html
{% extends "homepage.html" %}

{% load i18n %}

{% block caption %}
  <div class="feature-columns row">
    <div class="col-md text-center">
        <h3>All Staff</h3>
          <ul class="list-unstyled">
          {% for staff in all_staff %}
              <li>{% if not user.is_active %}Not active {% endif %}{% if user.account.is_manager %}<a class="day_nav" href="{{ staff.get_absolute_url }}">{{ staff }}</a>{% else %}{{ staff }}{% endif %}<a href="{% url 'staff_sced:staff_avail' staff.slug %}"> availability</a></li>
              {% empty %}
              <li>No Staff Logged</li>
          {% endfor %}
          </ul>
    </div>
  </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
{% endblock %}