HourClass/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import routers
# from rest_framework.authtoken import views
from account.views import SignUpAPI, PasswordResetTokenAPI, PasswordResetAuthAPI
from consumer.views import ClientMemberViewSet
from service.views import ServicesViewSet, GetEventApi
from staffer.views import StaffMemberViewSet
from event.views import (
    ClientEventViewSet,
    GetDateForEventApiList,
    GetAvailForAppointmentList,
    EventCreateAPI,
    EventUpdateAPI,
    EventCancelAPI
    )
from consortium.views import CompanyDetailsViewSet
from source_utils.views import HomeDetail
from source_utils.permission_mixins import CustomAuthToken, ChangePasswordView
# from rest_framework.authtoken.views import ChangePasswordView

from django.contrib import admin

router = routers.DefaultRouter()
router.register(r'services', ServicesViewSet)
router.register(r'recent_appointments', ClientEventViewSet)
router.register(r'active_staff', StaffMemberViewSet)
router.register(r'company_details', CompanyDetailsViewSet)
# router.register(r'server_time', GetDateForEventApiList, base_name='server_time')


from rest_auth.views import LoginView


urlpatterns = [
    path("", HomeDetail.as_view(), name="home"),
    re_path(r'^schedule/(?P<day>-?\d+)/$', HomeDetail.as_view(), name="home_schedule"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', CustomAuthToken.as_view()),
    path('rest-auth/', include('rest_auth.urls')),
    path('sign_up/', SignUpAPI.as_view(), name='sign_up'),
    path('get_reset_pin/', PasswordResetTokenAPI.as_view(), name='get_reset_pin'),
    path('get_reset_auth/', PasswordResetAuthAPI.as_view(), name='get_reset_auth'),
    # url(r'^$',EmployeeTemplateView.as_view(emp='employees')
    path('available_appt_dates/', GetDateForEventApiList.as_view(), name='available_appt_dates'),
    path('available_appt_times/', GetAvailForAppointmentList.as_view(), name='available_appt_times'),
    path('create_event_api/', EventCreateAPI.as_view(), name='create_event_api'),
    path('update_event_api/', EventUpdateAPI.as_view(), name='update_event_api'),
    path('cancel_event_api/', EventCancelAPI.as_view(), name='cancel_event_api'),
    path('get_event_api/', GetEventApi.as_view(), name='get_event_api'),
    path('rest-auth/login/', LoginView.as_view(), name='rest_login'),
    path('reset_password/', ChangePasswordView.as_view(), name='reset_password'),

    path("service/", include("service.urls")),
    path("event/", include("event.urls")),
    path("client/", include("consumer.urls")),
    path("staff_schedule/", include("staff_sced.urls")),
    path("staff/", include("staffer.urls")),
    path("company/", include("consortium.urls")),

    path("client_users/<str:username>/<str:hello>/", ClientMemberViewSet.as_view({'get': 'list'})),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# from rest_framework.authtoken import views
# urlpatterns += [
#     url(r'^api-token-auth/', views.obtain_auth_token)
# ]

consortium/urls.py
from django.urls import path

from .views import (
    CompanyUpdate,
    DayList,    
    DayUpdate
)
# get_day

app_name = 'consortium'
urlpatterns = [
    path('hours_of_operation/', DayList.as_view(),
        name="work_days"),
    # path('<slug:slug>/avail/', AvailabilityList.as_view(),
    #     name="staff_avail"),
    # path('all_events/', AllEventList.as_view(),
    #     name="all_event_list"),
    # path('add_client_appt/', ClientApptCreate.as_view(),
    #     name="add_client_appt"),
    path('<int:pk>/update/', CompanyUpdate.as_view(),
        name="company_details"),
    # path('staff_event/<int:pk>/update/', StaffEventUpdate.as_view(),
    #     name="staff_event_update"),
    # path('find/<slug:service>/<slug:client>/<slug:staff>/<str:date>/', AvailForAppointmentList.as_view(),
    #     name="avail_appt_list"),
    # path('<str:start>/<slug:sel_ser>/<slug:staff>/<slug:client>/create/', ClientEventCreate.as_view(),
    #     name="client_event_create"),
    path('<int:pk>/day_update/', DayUpdate.as_view(),
        name="get_day"),
    # url(r'^base/(?P<slug>[-\w]+)/update/$', BaseTypeUpdate.as_view(),
    #     name="service_update"),

    # url(r'^service/manage/(?P<slug>[-\w]+)/$', manage_service,
    #     name="service_manage"),
]

event/urls.py
from django.urls import path, re_path

from .views import (
    AllEventList,
    AvailForAppointmentList,
    # AvailabilityList,
    # ClientApptCreate,
    ClientEventCreate,
    ClientEventUpdate,
    GetDateForEvent,
    GetClientForEvent,
    GetTypeOfEvent,
    GetStaffForEvent,
    # MyAvailCreate,
    # MyAvailUpdate,
    MyEventList,    
    StaffEventUpdate
)


app_name = 'event'
urlpatterns = [
    path('my_events/',
        MyEventList.as_view(),
        name="my_event_list"),
    # path('<slug:slug>/avail/',
    #     AvailabilityList.as_view(),
    #     name="staff_avail"),
    path('all_events/',
        AllEventList.as_view(),
        name="all_event_list"),
    path('add/event/',
        GetClientForEvent.as_view(),
        name="start_new_client_appt"),
    path('add/<int:client>/<str:ev_type>/',
        GetTypeOfEvent.as_view(),
        name="add_service_type"),
    path('add/<slug:service>/<int:client>/<str:ev_type>/',
        GetStaffForEvent.as_view(),
        name="add_staff_to_appt"),

    path('add/<str:selected_staff>/<slug:service>/<int:client>/<str:ev_type>/',
        GetDateForEvent.as_view(),
        name="add_date_to_appt"),
    
    path('<int:pk>/update/',
        ClientEventUpdate.as_view(),
        name="event_update"),
    path('staff_event/<int:pk>/update/',
        StaffEventUpdate.as_view(),
        name="staff_event_update"),

    path('find/<str:selected_staff>/<str:date>/<str:staff_name>/<slug:service>/<int:client>/<str:ev_type>/',
        AvailForAppointmentList.as_view(),
        name="avail_appt_list"),

    path('create/<str:start>/<str:staff>/<slug:service>/<int:client>/<str:ev_type>/',
        ClientEventCreate.as_view(),
        name="client_event_create"),
    # path('<int:pk>/avail_update/',
    #     MyAvailUpdate.as_view(),
    #     name="my_avail_update"),
    # path('<int:pk>/avail_create/',
    #     MyAvailCreate.as_view(),
    #     name="avail_create"),



    
    # url(r'^base/(?P<slug>[-\w]+)/update/$', BaseTypeUpdate.as_view(),
    #     name="service_update"),

    # url(r'^service/manage/(?P<slug>[-\w]+)/$', manage_service,
    #     name="service_manage"),
]

service/urls.py
from django.urls import path, re_path

from .views import (
    ServiceList, ServiceUpdate, ServiceCreate
    # BranchList, BranchCreate, BranchUpdate, BaseTypeCreate,
    # BaseTypeDetail, BaseTypeUpdate, manage_service
)


app_name = 'service'
urlpatterns = [
    re_path(r'^services/$', ServiceList.as_view(),
        name="service_list"),
    re_path(r'^create/$', ServiceCreate.as_view(),
        name="service_create"),
    re_path(r'^(?P<slug>[-\w]+)/update/$', ServiceUpdate.as_view(),
        name="service_update"),

    # url(r'^base/(?P<slug>[-\w]+)/create/$', BaseTypeCreate.as_view(),
    #     name="service_create"),
    # url(r'^base/(?P<slug>[-\w]+)/$', BaseTypeDetail.as_view(),
    #     name="service_detail"),
    # url(r'^base/(?P<slug>[-\w]+)/update/$', BaseTypeUpdate.as_view(),
    #     name="service_update"),

    # url(r'^service/manage/(?P<slug>[-\w]+)/$', manage_service,
    #     name="service_manage"),
]

staffer/urls.py
from django.urls import path, re_path

from .views import SignupStaffView, StaffList, StaffUpdate
# from event.views import AvailabilityList


app_name = 'staff'
urlpatterns = [
    # path('<slug:slug>/availability/', AvailabilityList.as_view(),
    #     name="staff_avail"),
    path('all_staff/', StaffList.as_view(),
        name="all_staff"),
    path('add_staff/', SignupStaffView.as_view(),
        name="add_staff"),
    path('<int:pk>/update/', StaffUpdate.as_view(),
        name="staff_update"),
    # path('staff_event/<int:pk>/update/', StaffEventUpdate.as_view(),
    #     name="staff_event_update"),
    # path('find/<slug:service>/<slug:client>/<slug:staff>/<str:date>/', AvailForAppointmentList.as_view(),
    #     name="avail_appt_list"),
    # path('<str:start>/<slug:sel_ser>/<slug:staff>/<slug:client>/create/', ClientEventCreate.as_view(),
    #     name="client_event_create"),
    # url(r'^base/(?P<slug>[-\w]+)/update/$', BaseTypeUpdate.as_view(),
    #     name="service_update"),

    # url(r'^service/manage/(?P<slug>[-\w]+)/$', manage_service,
    #     name="service_manage"),
]

HourClass/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="navbar-nav" style="background-color: transparent;">
    <li class="nav-item">
        <a class="nav-link" href="{% url "home" %}">{% trans "Home" %}</a>
    </li>
    {% if request.user.is_authenticated %}
    {% if request.user.is_authenticated and not request.user.is_staff %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'event:add_service_type' request.user.account.pk  'for_client' %}">{% trans "Book Apptointment" %}</a>
    </li>
    {% endif %}
    {% if user.is_staff %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'event:add_service_type' request.user.account.pk 'for_staff' %}">{% trans "Book My Appt" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'event:start_new_client_appt' %}">{% trans "Book Client Appt" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'event:my_event_list' %}">{% trans "Calendar" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'staff:all_staff' %}">{% trans "Staff" %}</a>
    </li>
    {% endif %}
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'service:service_list' %}">{% trans "Services" %}</a>
    </li>
    {% if user.account.is_manager %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'consortium:company_details' 1 %}">{% trans "Company" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'event:all_event_list' %}">{% trans "All CL Appts" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'consortium:work_days' %}">{% trans "Open/Time" %}</a>
    </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_settings' %}">{% trans "Settings" %}</a>
    </li>
        {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
            </li>
        {% endif %}
    <li class="nav-item">
        <a class="nav-link" id="account_logout" href="{% url 'account_logout' %}">{% trans "Log out" %}</a>
    </li>
    {% else %}
    <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
    {% if ACCOUNT_OPEN_SIGNUP %}
        <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
    {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

HourClass/templates/_footer.html
{% load i18n %}

{% now "Y" as current_year %}
<footer class="footer">
	<div class="container" style="background-color: transparent;">
		<div class="copyright text-center"><span>&copy; {{ current_year }} {{ company }}</span><span>{{ company.company_phone }}</span><span>{{ company.email }}</span></div>
	</div>
</footer>

HourClass/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="57x57" href='{% static "img/apple-icon-57x57.png" %}'>
        <link rel="apple-touch-icon" sizes="60x60" href='{% static "img/apple-icon-60x60.png" %}'>
        <link rel="apple-touch-icon" sizes="72x72" href='{% static "img/apple-icon-72x72.png" %}'>
        <link rel="apple-touch-icon" sizes="76x76" href='{% static "img/apple-icon-76x76.png" %}'>
        <link rel="apple-touch-icon" sizes="114x114" href='{% static "img/apple-icon-114x114.png" %}'>
        <link rel="apple-touch-icon" sizes="120x120" href='{% static "img/apple-icon-120x120.png" %}'>
        <link rel="apple-touch-icon" sizes="144x144" href='{% static "img/apple-icon-144x144.png" %}'>
        <link rel="apple-touch-icon" sizes="152x152" href='{% static "img/apple-icon-57x57.png" %}'>
        <link rel="apple-touch-icon" sizes="180x180" href='{% static "img/apple-icon-180x180.png" %}'>
        <link rel="icon" type="image/png" sizes="192x192"  href='{% static "img/android-icon-192x192.png" %}'>
        <link rel="icon" type="image/png" sizes="32x32" href='{% static "img/favicon-32x32.png" %}'>
        <link rel="icon" type="image/png" sizes="96x96" href='{% static "img/favicon-96x96.png" %}'>
        <link rel="icon" type="image/png" sizes="16x16" href='{% static "img/favicon-16x16.png" %}'>
        <link rel="manifest" href="img/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content='{% static "img/ms-icon-144x144.png" %}'>
        <meta name="theme-color" content="#ffffff">
        <title>{% block head_title_base %} Scheduler | {% block head_title %}{% endblock %}{% endblock %}</title>
        {% block viewport %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% endblock %}

        {% block styles %}{% endblock %}

        {% block html5shim %}
            <!-- HTML5 shim, for IE6-8 support of HTML elements -->
            <!--[if lt IE 9]>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
            <![endif]-->
        {% endblock %}

        {% block extra_head_base %}
            {% block extra_head %}{% endblock %}
        {% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}" {% block body_extra_attributes %}{% endblock %}>
        <div class="{% block wrapper_class %}{% endblock %}">

            {% block topbar_base %}
                <header>
                    <div class="navbar navbar-default {% block navbar_class %}navbar-fixed-top{% endblock %}">
                        <div class="container">
                        {% block topbar %}
                            <div class="navbar-header">
                                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="fa fa-bars"></span>
                                </button>
                                {% block site_brand %}<a class="navbar-brand" href="{% url "home" %}">{{ SITE_NAME }}</a>{% endblock %}
                            </div>
                            <div class="collapse navbar-collapse navbar-responsive-collapse">
                                {% block nav %}
                                    {% comment %}
                                        <ul class="nav navbar-nav">
                                            <li><a href="#tab_one">One</a></li>
                                            <li><a href="#tab_two">Two</a></li>
                                        </ul>
                                    {% endcomment %}
                                {% endblock %}
                                {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
                            </div>
                        {% endblock %}
                        </div>
                    </div>
                </header>
            {% endblock %}

            {% block body_base %}
                <section id="content_body">
                    <div class="container">
                        {% include "_messages.html" %}
                        {% block body %}
                        {% endblock %}
                    </div>
                </section>
            {% endblock %}

            {% block footer_base %}
                <hr />
                <footer>
                    <div class="container">
                        {% block footer %}{% endblock %}
                    </div>
                </footer>
            {% endblock %}
        </div>

        {% block scripts %}{% endblock %}

        {% block theme_script %}
            <script src="{% static "pinax/js/theme.js" %}"></script>
        {% endblock %}

        {% block extra_body_base %}
            {% block extra_body %}{% endblock %}
        {% endblock %}
    </body>
</html>

HourClass/templates/form.html
{% extends "homepage.html" %}

{% load i18n %}

{% load crispy_forms_tags %}
{% load bootstrap %}

{% block head_title %}{{ title }}{% endblock %}

{% block caption %}
    <div class="panel panel-default">
        <div class="panel-heading text-center">
            <legend>{{ title }} {{ add }}{% if titleb %}<br />{{ titleb }}{% endif %}{% if titlec %}<br />{{ titlec }}{% endif %}{% if titled %}<br />{{ titled }}{% endif %}
                {% block edit %}{% endblock %}
                {% if object.extra %}
                    {{ object.extra }}
                {% endif %}
            </legend>      
            <div class="list-group">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div id="formWarning">{{ form_warning }}</div>
                    <input type="button" class="cancel_btn pointer" value="Back" onclick="window.history.go(-1);"/>
                    <input type="submit" class="submit_btn pointer" value="{{ button }}" />
                </form>
            </div> 
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
{% endblock %}

HourClass/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load tz %}
{% load staticfiles %}
{% load custom_tags %}

{% block head_title %}Home{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}

<main>
  <div>
    <section class="jumbotron" style="background-color: #7BC9E3;">
        <div class="container">
            {% include "_messages.html" %}
            {% block caption %}
            {% if user.is_authenticated and user.is_staff %}
            <div class="feature-columns row">
                <div class="col-md text-center">
                    <div><h3><a class="day_nav go_left" href="{% url 'home_schedule' real_date|sub_one_day %}">prev</a>{{ the_day }}<a class="day_nav go_right" href="{% url 'home_schedule' real_date|add_one_day %}">next</a></h3></div>
                    <p class="lead">
                        <ul class="list-unstyled">
                        {% for event in all_my_events_today %}
                            <li>{% if event.status %}{% if event.check_for_update %}<a class="gen_alert" href="{{ event.get_absolute_url }}">{{ event.get_freindly_times }}</a>{% else %}<a href="{{ event.get_absolute_url }}">{{ event.get_freindly_times }}</a>{% endif %}-{{ event.get_service }} with <a href="{{ event.get_client_absolute_url }}">{{ event.get_client_iter }}</a>{% else %}<span class="gen_alert">*</span><span class="{% if event.start > nowr %}now_decor{% endif %}">{{ event }}</span>{% endif %}</li>
                            {% empty %}
                            <li>No Appointments</li>
                        {% endfor %}
                        </ul>
                    </p>
                </div>
                {% if user.is_authenticated and user.account.is_manager %}
                <div class="col-md text-center">
                    <h3>Staff Schedule</h3>
                    <p class="lead">
                        <ul class="list-unstyled">
                        {% for event in all_staff_events_today %}
                            <li>{% if event.status %}{% if event.check_for_update %}<span class="gen_alert">{{ event.get_freindly_times }}</span>{% else %}<a href="{{ event.get_absolute_url }}">{{ event.get_freindly_times }}</a>{% endif %}-{{ event.get_service }} for <a href="{{ event.get_client_absolute_url }}">{{ event.get_client_iter }}</a> with {{ event.get_staff }}{% else %}<span class="gen_alert">*</span>{{ event }}{% endif %}</li>
                            {% empty %}
                            <li>No Appointments</li>
                        {% endfor %}
                        </ul>
                    </p>
                </div>
                {% endif %}
            </div>
            {% elif user.is_authenticated %}
            <h1>Welcome {{ this_user.first_name }}!</h1>
            <p class="lead">
                We are happy to book you in for an appointment with us. Please veiw our calendar or select one of our associates.
            </p>
            <div class="col-md text-center">
            {% if my_personal_booking %}
                <h4>My next appointments are:</h4>
                <ul class="list-unstyled">
                {% for event in my_personal_booking %}
                    <li>{{ event.get_service }} with {{ event.get_staff }} - {{ event.start }}!</li>
                {% endfor %}
                </ul>
                <h6>We look forward to seeing you!</h6>
            {% endif %}
            </div>
            {% else %}
            <h1 class="text-center">{% blocktrans %}Welcome to {{ company }}{% endblocktrans %}</h1>
            <h3 class="text-center">
                {{ company.caption }}
            </h3>
            {% url "account_login" as login_url %}
            {% url "account_signup" as signup_url %}
            <p class="mb-5 lead text-center">{% blocktrans %}You can <a href="{{ login_url }}" class="btn btn-secondary">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to use our site.{% endblocktrans %}</p>
            <p class="lead text-center">
                {{ company.bio }}
            </p>
            {% endif %}
            {% endblock %}
        </div>
        <div id="content-body" class="container">
            {% block main_theme %}
            {% if not user.is_staff and company %}
                <div class="feature-columns row">
                    <div class="col-md text-center">
                        <div class="desc">
                            <b>{{ company }} Services</b><br />
                            <ul class="list-unstyled">
                            {% for branch in service_branches %}
                            <li>{{ branch }}</li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-md text-center">
                        <div class="desc">
                            <b>Meet our Staff</b><br />
                            <ul class="list-unstyled">
                            {% for member in staff %}
                            <li>{{ member.get_friendly_name }}</li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-md text-center">
                        <div class="desc">
                            <b>Popular Services</b><br />
                            <ul class="list-unstyled">
                            {% for service in popular_services %}
                            <li>{{ service.retail_service }}<i> only </i>${{ service.get_tot_service_cost }}</li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        {% endblock %}
    </section>
  </div>
</main>
{% endblock %}
{% block footer %}
    {% include "_footer.html" %}
{% endblock %}

HourClass/templates/site_base.html
{% extends "base.html" %}

{% load staticfiles %}
{% load pinax_webanalytics_tags %}
{% load i18n %}


{% block styles %}
    <!-- <link href="{% static "css/site.css" %}" rel="stylesheet" /> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="css/homepage.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static "css/home.css" %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}


{% block extra_head_base %}
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block topbar_base %}
<header>
    <div class="navbar fixed-top {% block navbar_class %}navbar-expand-lg navbar-dark bg-dark{% endblock %}">
        <div class="container">
        {% block topbar %}
            {% block site_brand %}<span class="navbar-brand" href="{% url "home" %}">
            {% if request.user.is_staff %} {{ request.user.get_name_abr }}{% else %}{{ company.company_phone }}{% endif %}</span>{% endblock %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="fa fa-bars"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% block nav %}
                    <ul class="navbar-nav mr-auto">
                        {% block nav_items %}{% comment %}
                        <li class="nav-item"><a class="nav-link" href="#tab_one">One</a></li>
                        <li class="nav-item"><a class="nav-link" href="#tab_two">Two</a></li>
                        {% endcomment %}{% endblock %}
                    </ul>
                {% endblock %}
                {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
            </div>
        {% endblock %}
        </div>
    </div>
</header>
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    <!-- <script src="{% static "js/site.js" %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}